name: example-app
channels:
- defaults
- conda-forge
dependencies:
- python=3
- flask
- requests
- flask-restful
- numpy
- pandas
- pip:
  - imbalanced-learn
  - imblearn
  - scikit-learn
  - sklearn
